project:
  type: website

website:
  title: "VAA_Group2_Apr2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Proposal
        href: project_timeline.qmd
      - text: App
        href: https://vaagroup2apr2023.shinyapps.io/vaa_project/
      - about.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

