project:
  type: website

website:
  title: "VAA_Group2_Apr2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Proposal
        href: proposal.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

